import mysql.connector

mydb = mysql.connector.connect(
    host="192.168.18.63",
    user="newuser",
    passwd='root',
    database="dblp"
)

mycursor = mydb.cursor(buffered=True)

search_abbreviated_journal_titles = "SELECT name FROM dblp.journal where `name` like '%.%'"
search_abbreviated_journal_titles_in_FOR = "SELECT * FROM dblp.journalsfor where Title like %s"

mycursor.execute(search_abbreviated_journal_titles)

abbrv_titles = list(sum(mycursor.fetchall(), ()))

result = list(set(word for title in abbrv_titles for word in title.split() if '.' in word))

# print("\':\'\',\n\'".join(result) + ':,\'')

abbrv_match = {
    'Meth.': 'Methodology',
    'I.': 'International',
    'Transm.': 'Transmission',
    'Neurorobot.': 'Neurorobotics',
    'Sci.,': 'Science',
    'Astronom.': 'Astronomiques',
    'Strat.': 'Strategic',
    'Softw.,': 'Software',
    'Polon.': 'Polonaise',
    'Log.': 'Logic',
    'Knowl.': 'Knowledge',
    'Adv.': 'Advances',
    'Visualiz.': 'Visualization',
    'Lang.': 'Language',
    'Contr.': 'Control',
    'Prog.': 'Programming',
    'Symb.': 'Symbolic Computation',
    'Dynam.': 'Dynamics',
    'Environ.': 'Environments',
    'Intell.': 'Intelligent',
    'Automat.': 'Automation',
    'Rev.': 'Review',
    'Serv.': 'Services',
    'Modul.': 'Modularity',
    'Indust.': 'Industrial',
    'J.': 'Journal',
    'Neurosci.': 'Neuroscience',
    'Vis.': 'Vision',
    'Oper.': 'Operations',
    'Funct.': 'Functional',
    'Mod.': 'Models',
    'Num.': 'Numerical',
    'Soc.': 'Society',
    'Inform.,': 'Informaticae',
    'Comb.': 'Combinatorial',
    'Infrastruct.': '',
    'Cogn.': '',
    'Dept.': '',
    'Natl.': '',
    'Process.': '',
    'Discret.': '',
    'Lith.': '',
    'Dev.': '',
    'Translat.': '',
    'Nachr.': '',
    'Appl.': 'Applications',
    'Test.,': '',
    'Learn.': 'Learning',
    'Reliab.': '',
    'Connect.': '',
    'Comm.': '',
    'Forsch.': '',
    'Sig.': '',
    'Optim.': '',
    'Secur.': 'Security',
    'Manage.': '',
    'Intellig.': 'Intelligent',
    'Netw.': 'Networks',
    'Observ.': '',
    'Exp.': '',
    'U.S.A.': '',
    'Model.': '',
    'Biomed.': '',
    'Europ.': '',
    'Nord.': '',
    'Electron.': '',
    'Lett.': 'Letters',
    'Mag.': 'Magazine',
    'Techn.': '',
    'Mach.': 'Machine',
    'Struct.': '',
    'Alg.': '',
    'Embed.': '',
    'Lin.': '',
    'Univ.': '',
    'Zeitschr.': '',
    'Bioinform.': '',
    'Ann.': '',
    'Trans.': 'Transactions',
    'Publ.': '',
    'Prof.': '',
    'Requir.': '',
    'Surg.': '',
    'Interact.': '',
    'Graph.': '',
    '(Lond.)': '',
    'meltdownattack.com': '',
    'Bio.': '',
    'Proc.:': '',
    'Asp.': '',
    'Fundam.': 'Fundamenta',
    'Communic.': '',
    'Entwickl.': '',
    'Neurosc.': '',
    'e-Technol.': '',
    'Distrib.': '',
    'Arch.': 'Archive',
    'Verif.': '',
    'Discov.': '',
    'Meet.': '',
    'Exper.': '',
    'Autom.': '',
    'Interdiscip.': '',
    'Syst.': 'Systems',
    'Cybern.': '',
    'Probl.': '',
    'Sér.': 'Série',
    'Front.': 'Frontiers',
    'Tran.': '',
    'Softw.': '',
    'Des.': '',
    'Auton.': '',
    'Robot.': 'Robotics',
    'Approx.': '',
    'Sign.': '',
    'Eur.': '',
    'Eval.': '',
    'Phys.': 'Physical',
    'Dok.': '',
    'Computat.': 'Computing',
    'Pr.': '',
    'Math.': 'Mathematics',
    'Artif.': '',
    'Sel.': '',
    'Wiss.': '',
    'Compos.': 'Composition',
    'Pract.': '',
    'Mech.': '',
    'Inf.': 'Information',
    'Priv.': '',
    'Cryptol.': '',
    'Electr.': '',
    'Q.': '',
    'Neuroinform.': '',
    'Uncertain.': '',
    'Imag.': '',
    'Wirtschaftsinform.': '',
    'Env.': '',
    'Retr.': '',
    'Instrum.': '',
    'Cyper-Phys.': '',
    'Stud.': '',
    'Surv.': '',
    'Control.': '',
    'E.': '',
    'Digit.': '',
    'Int.': '',
    'Reconfig.': '',
    'Sci.': '',
    'Algebr.': '',
    'Comput.': 'Computational',
    'Med.': '',
    'Opt.': '',
    'Technol.:': '',
    'Hum.': '',
    'Sec.': '',
    'Rel.': '',
    'Analys.': '',
    'Multidim.': '',
    'Anal.': '',
    'Emerg.': '',
    'Simul.': '',
    'Cyberpsy.,': '',
    'T.': '',
    'Bull.': 'Bulletin',
    'Emb.': '',
    'Hardw.': '',
    'Radiol.': '',
    'Min.': '',
    'Acad.': 'Académie',
    'Cryptogr.': '',
    'Hum.-Comput.': '',
    'Mob.': '',
    'Biol.': '',
    'Contemp.': '',
    'Edu.': '',
    'Chang.': '',
    'Manag.': '',
    '5.10': '',
    'Found.': '',
    'Comput.-Hum.': '',
    'User-Adapt.': '',
    'Educat.': '',
    'Methodol.': '',
    'Proc.': '',
    'Applic.': '',
    'Inform.': 'Information',
    'Res.': 'Research',
    'Semant.': '',
    'I.R.E.': '',
    'Program.': 'Programming',
    'Knowl.-Based': '',
    'Commun.': '',
    'Theor.': '',
    'Meas.': '',
    'Sys.': '',
    'Org.': '',
    'Ser.': 'Series',
    'Geosci.': '',
    'Braz.': '',
    'Geom.': '',
    'Rep.': '',
    'Eng.': 'Engineering',
    'Transport.': 'Transportation',
    'Technol.': '',
    'Austr.': '',
    'Assist.': '',
    'Comp.': '',
    'Comp.-Aided': '',
    'Topol.': '',
    'Perform.': ''
}

mycursor.close()
mydb.close()
